### ISSUE TITLE
src/blog/2008/mercurial-basics.md

### ISSUE THREAD

**Issue by Juev** [piranha/solovyov.net#3]
Привет.

Читаю твои статьи по mercurial, натолкнулся на ряд неточностей или непоняток. Но обо всем по порядку. Там где смогу сам поправить, форкну и поменяю. А вот тут не понятно, либо команду упустил, либо текст оформлен не правильно. Что здесь подразумевается??
```
Всё начинается с того, что мы создаём репозиторий:

Если посмотреть внутрь директории `repo`, можно увидеть директорию `.hg`
- это и есть сам репозиторий, в котором хранятся ревизии и настройки
данного конкретного экземпляра (репозитория, простите за каламбур ;).
Начать можно с добавления файлов и коммита первой ревизии:
```

Имя файла указано в имени issue

**Comment by piranha** [comment]
Починил :)

**Comment by Juev** [comment]
Спасибо! ☺️
