### ISSUE TITLE
incorrectly rendered footnotes

### ISSUE THREAD

**Issue by vthriller** [piranha/solovyov.net#5]
Список есть, а контента нет:

```html
<div class="footnotes">
<hr>
<ol>
<li id="fn:https-addons-mozilla-org-en-US-firefox-addon-9602"></li>
</ol>
</div>
```

Например:
- https://solovyov.net/blog/2008/poor-mans-rebase-in-mercurial/
- https://solovyov.net/blog/2008/musicx/
- https://solovyov.net/blog/2008/firepython-no-prints/
- https://solovyov.net/blog/2009/revcanonical/

**Comment by vthriller** [comment]
Я ждал этот ответ (-:

У меня, впрочем, есть подозрение, что дело в урлах, сваленных в конец, за тело сносок. Его даже подтверждает беглый `fgrep -r ^1 2008`, выдающий [старьё, в котором такая фигня не воспроизводится](https://solovyov.net/blog/2008/postgres-is-not-slow/).

**Comment by piranha** [comment]
А, слушай, действительно, текст-то там есть. Спасибо, ща исправлю. )

**Comment by piranha** [comment]
done )
